name = input("Enter Your Name: ")
studentid = input("Enter student id: ")
course = input("Enter course: ")
college = input("Enter College name: ")
dob = input("Enter date of birth: ")
group = input("Enter blood group: ")
print("    STUDENT ID CARD     ")
print("Name        :  " +name)
print("StudentId   :  " +studentid)
print("Course      :  " +course)
print("College     :  " +college)
print("DateOfBirth :  " +dob)
print("Blood Group :  " +group)